name:               "听楼一夜雨"
description:        "时间顺流而下，生活逆舟前行。"

url:                "https://gitlk.github.io"
author:             "lk"
email:              "913887798@qq.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "听楼一夜雨"
email:              "913887798@qq.com"
github:             "gitlk"
pinterest:          "听楼一夜雨"
linkedin:           "听楼一夜雨"
facebook:           "听楼一夜雨"

disqus_shortname:   "听楼一夜雨"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "about"
  - name:           "Download"
    href:           "releases"
  - name:           "Blog"  
    href:           "CV"
sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate