name: "LK的博客"
email: "913887798@qq.com"
author: "lk"
url: "https://gitlk.github.io/"
resume_site: "https://gitlk.github.io/CV/"
github: "https://github.com/gitlk/"
baseurl: "/"
description: "如有问题请用邮件联系我：913887798@qq.com"
meta_description: "lk;个人博客;时间顺流而下;生活逆舟而行;生命不止;折腾不休"
motto: "It's our wits that make us men."
banner: "时间顺流而下;生活逆舟而行。"


permalink: "/:year/:month/:day/:title/
paginate: "10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: "gitlk"
highlighter: "Pygments"


markdown: "kramdown"

baidu_analysis: "94be4b0f9fc5d94cc0d0415ea6761ae9"

disqus_shortname:   "lkgit"


